version: '3.8'
services:
  sqlserver:
    build:
      context: .
      dockerfile: sqledge.Dockerfile
    container_name: sqltemp
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=DevPassword123#
      - MSSQL_PID=Developer
      # Disable encryption requirement for local dev
      - MSSQL_ENCRYPT=DISABLED
    ports:
      - "1433:1433"
    volumes:
      - ../temp_data:/var/opt/mssql/backup
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P "DevPassword123#" -C -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s


  postgres:
    image: postgres:15
    container_name: pg_target
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vpic
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # postgres:
  #   image: postgres:15
  #   container_name: pg_target
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=vpic
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   command: 
  #     - postgres
  #     - "-c"
  #     - "listen_addresses=*"
  #     - "-c"
  #     - "password_encryption=md5"

  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
      
  # postgres:
  #   image: postgres:15
  #   container_name: pg_target
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=vpic
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   command: 
  #     - "postgres"
  #     - "-c"
  #     - "password_encryption=md5"
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

volumes:
  postgres_data: